### PR TITLE
Add missing description for the settings panel (fixes #1677)

### LINKED ISSUE #1677: Missing description for Go section in the settings UI in build 0.9.346
Just installed the latest release.  Looking at the `Settings > Languages & Frameworks > Go` and it has `!go.settings.description!`.  I'm guessing that was a bug/oversight

image

### PR DESCRIPTION
**Pull request by dlsniper**

### CODE REVIEW

**Comment by wuchuguang** [comment]
how to fix already install to intellij?
now , can open setting panel to reinstall go plugin

**Comment by dlsniper** [comment]
@wuchuguang I'm sorry, unfortunately I don't understand the question. This change is done for cosmetics, it doesn't impact the plugin functionality in a meaningful way.

If you want to get the latest version of the plugin, please follow the instructions here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds

**Comment by wuchuguang** [comment]
I IDE you go the plug-in has been installed, before you go plug-in installed, result in setting the panel to open it (CTRL + Alt + s) are invalid
I now how to fix it?

**Comment by wuchuguang** [comment]
I am under Linux , use intellij

**Comment by dlsniper** [comment]
@wuchuguang can you please open a new issue for this? Also, please include a screenshot of the problem and log files ``` Help | Show Log in File Manager ```. Thank you.

**Comment by dlsniper** [comment]
Ping for this one as well? (it still happens in IDEA 15)

**Comment by zolotov** [comment]
Won't fix in plugin, it's platform issue

**Pull request closed without merging**
