### PR TITLE
Improve the json live template

### PR DESCRIPTION
**Pull request by dlsniper**
I've been using this for a while now and it's easier to use than having the backticks as well.

### CODE REVIEW

**Comment by zolotov** [comment]
1. why?
2. will it be available inside backticks
3. description doesn't match value

**Comment by dlsniper** [comment]
> 1. why?

I usually find myself typing the backtick (since IntelliJ will complete the other one) and then type jso<enter> When that happens I get two backticks then I have to manually fix this. 

> 2. will it be available inside backticks

yes, it seems to be working fine

> 3. description doesn't match value

I've fixed it, sorry.

**Comment by dlsniper** [comment]
If there's a better way to fix the double backtick issue then that would be great (aside from changing how I type it, unfortunately it's in muscle memory by now).

**Comment by zolotov** [comment]
> I usually find myself typing the backtick (since IntelliJ will complete the other one) and then type jso When that happens I get two backticks then I have to manually fix this.

Then change these templates in your IDE. Changing template in plugin affects all users who got used to these templates.

> If there's a better way to fix the double backtick issue then that would be great (aside from changing how I type it, unfortunately it's in muscle memory by now).

I believe there are some methods to fix it, file an issue please.

**Comment by dlsniper** [comment]
Will do, thanks.

**Pull request closed without merging**
