### PR TITLE
Fixing the javac2 class location to the default Idea path

### PR DESCRIPTION
**Pull request by letsjustfixit**
It's nothing really just a path change but can be annoying :)

### CODE REVIEW

**Comment by mtoader** [comment]
Please rebase to latest master.

**Comment by dlsniper** [comment]
Also, if you want to build the plugin from the command line, look at how we
do it for TravisCI
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/coverity.sh

**Comment by letsjustfixit** [comment]
@mtoader I'm sorry I'll do so :)
@dlsniper I'm building via the intellij ide with the ant plugin.

**Comment by dlsniper** [comment]
There's no need for that. Just use Build -> Prepare plugin for deployment (last option in the Build menu). And that's it.

**Comment by dlsniper** [comment]
I'll close this one as 1.0.0 doesn't present this issue and it's overriding the 0.9.x branch

**Pull request closed without merging**
