### PR TITLE
Update docker to the latest version

### PR DESCRIPTION
**Pull request by dlsniper**
As Docker 1.5 is deprecated and soon docker hub will stop working with 1.5 version, I think this version should be updated. Please see the following link for details: https://blog.docker.com/2015/10/docker-hub-deprecation-1-5/
Hope it helps.

### CODE REVIEW

**Comment by zolotov** [comment]
Broken tests: https://teamcity.jetbrains.com/viewLog.html?buildId=632459&tab=buildResultsDiv&buildTypeId=IntellijIdeaPlugins_Go_PerformanceTests

**Comment by dlsniper** [comment]
Ah, I think I should have read the sources better, Go and Docker are used only for the source code not for the actual functionality.
Let me know if I should add the changes to fix this or not in this context.
And as a final question, shouldn't kubernetes be added as part of the tests as the kubernetes source tree is about 2x larger in number of files and 3x larger in terms of lines of code?

**Comment by zolotov** [comment]
> Let me know if I should add the changes to fix this or not in this context.

Updating docker makes sense probably. Not for performance testings but for inspections. Anyway if you want to change the testdata you should check all mismatched inspection reports: maybe by updating docker you revealed some bug. 

> And as a final question, shouldn't Kubernetes be added as part of the tests as the kubernetes source tree is about 2x larger in number of files and 3x larger in terms of lines of code?

I think we're fine with docker sources so far.

**Comment by dlsniper** [comment]
I've updated the files with the tests. I've sampled a few results for correctness and it looked ok. Unfortunately from what I can see the TeamCity integration doesn't work if I to a squash and a force push into the branch (or I don't know where to look for it at least).

**Comment by dlsniper** [comment]
Disregard the TeamCity part, it seems it takes a bit to queue it. Inow see a build in pending state.

**Comment by zolotov** [comment]
So have you figured out why there is a unused import?

**Comment by dlsniper** [comment]
Yes. The unused import actually is a redundant import declaration: ` import math "math"`. The description of the error was properly done.

**Pull request merged**
