### PR TITLE
Rework move to struct assignment intention by wbars

### PR DESCRIPTION
**Pull request by grenki**

### CODE REVIEW

**Comment by zolotov** [comment]
rebase please

**Comment by grenki** [comment]
rebased

**Comment by ignatov** [comment]
@wbars could you please sign JetBrains CLA – https://www.jetbrains.com/agreements/cla/

**Comment by wbars** [comment]
@ignatov was signed 16 oct

**Comment by ignatov** [comment]
Cool, couldn't find it in our agreement repository.

**Comment by ignatov** [comment]
@wbars Thanks a lot for the contribution.

**Comment by wbars** [comment]
@ignatov i'm going to improve this intention by `var s S` case in separate PR as we discussed before.

**Comment by ignatov** [comment]
Sure.

**Pull request merged**
