### PR TITLE
Initial support for the Go standard template language (text/template)

### PR DESCRIPTION
**Pull request by jhsx**
Continuation of #2167
@ignatov @zolotov 

Fixes https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/351

### CODE REVIEW

**Comment by zolotov** [comment]
Please add some tests for parser and lexer before continue. It's hard to validate anything without tests

**Comment by jhsx** [comment]
Ok i will do that as soon as i have time.

Thanks,
José Santos.

**Comment by mmindenhall** [comment]
Just curious...does this support the soon to be released [changes in go1.6](https://tip.golang.org/doc/go1.6#template)?

**Comment by zolotov** [comment]
@mmindenhall as soon as it will be covered with tests it will be merged. As for changes in 1.6, they aren't covered with this PR.

**Comment by dlsniper** [comment]
@zolotov, to confirm, the tests should be like these here:
- parser: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/tests/com/goide/parser/GoParserTest.java
- lexer: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/tests/com/goide/lexer/GoLexerTest.java

Correct? And if yes, how do I configure the test runner to show the coverage in the IDE for the tests (sorry if it's a stupid question but I couldn't find anything in the help section) and the IDE button to run with coverage is disabled for Gradle tests. Thank you!

**Comment by zolotov** [comment]
@dlsniper 

> the tests should be like these here

yes

> how do I configure the test runner to show the coverage in the IDE for the tests

There is no way to do it from IDE https://youtrack.jetbrains.com/issue/IDEA-148672. You may want to use JaCoCo gradle plugin or something else for that.

**Comment by dlsniper** [comment]
Could it be possible to have access to the coverage tab in TeamCity? I've asked for this a while ago: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2207 That way I could get this PR into a different branch of this repo, work on the tests, push them to TC to get the coverage without using JaCoCo or other workarounds. Thank you!

**Comment by zolotov** [comment]
@dlsniper added role at teamcity

**Comment by dlsniper** [comment]
Thank you!

**Comment by dlsniper** [comment]
I'll close this in favor of #2337 which has the commits in a different branch of the repository. As such tests could be written by more people / it will be easier to keep in sync with master. Thank you.

**Pull request closed without merging**
