### PR TITLE
Fix for #1784

### PR DESCRIPTION
**Pull request by chiknrice**

### CODE REVIEW

**Comment by zolotov** [comment]
It breaks #1507

**Comment by chiknrice** [comment]
can you let me know how you found it breaks #1507 as All Tests task run fine - what test could I run to catch these kind of issues in the future, thanks!

**Comment by zolotov** [comment]
I know that because pty processes were introduced initially in order to support coloring sequences in console.

Unfortunately it isn't covered with a test. Test requires running external process, real Go distribution and UI testing, and all these complexity doesn't correspond to potential impact of test.

**Comment by zolotov** [comment]
Anyway, thanks for discovering the connection between pty and #1784 bug, I didn't know that this is the reason.

**Pull request closed without merging**
