### PR TITLE
Introduce inspection to detect imported package names as identifier names

### PR DESCRIPTION
**Pull request by dlsniper**

### CODE REVIEW

**Comment by zolotov** [comment]
merged manually, thanks

**Comment by zolotov** [comment]
@dlsniper could you remind me what was the motivation of this inspection please? When is this useful?

**Comment by dlsniper** [comment]
Accidentally shadow a package name as then you can't use that for the rest of the scope you do it. There are users / code which does this and then users are baffled by why they can't use certain package functions or other exported identifiers.

**Comment by zolotov** [comment]
Ok, thanks

**Pull request closed without merging**
