### PR TITLE
Initial support for the Go standard template language (text/template)

### LINKED ISSUE #351: Support text / html templates
Golang offers templates in form of html and text.

It would be nice to investigate the capabilities of the templating system and see how we can add some support for it. I'm thinking of highlighting, goto provider, validation (?), check if any variable is missing at render time and so on.

I would keep this open here to list the features and keep track of them and then step by step add those features to the plugin.

Documentation reference:
- html: http://golang.org/pkg/html/template/
- text: http://golang.org/pkg/text/template/

Thanks.

### PR DESCRIPTION
**Pull request by dlsniper**
Continuation of #2180 which is now based on a local branch so that people can easily contribute to it with tests and other improvements and have this merged in master sooner rather than later.

I've maintained the original author for the commits as well.

Thank you for helping out making this possible.

Fixes #351

TODO:
- [ ] Tests for parser
- [ ] Tests for lexer
- [ ] Review

### CODE REVIEW

**Comment by dlsniper** [comment]
I've moved the template support to its own module. Hopefully this would make things cleaner. As the commit on itself is pretty big I'm not sure if it's reviewable.

Next I'll start with the parser tests and then lexer tests. I won't touch anything else in the code base until those two are done.

**Comment by jhsx** [comment]
Hi everyone, really sorry, because i am unable to delivery the tests in this pull request, i am not having time because of some personal issues.

@dlsniper if there is any thing that i can help by email or skype let me know and i will try to answer soon.

cc @ignatov @zolotov

**Comment by dlsniper** [comment]
@jhsx don't worry. I'll also have some downtime towards the end of the month as well. Thank you for your effort to make the PR possible in the first place.

**Comment by JReyLBC** [comment]
Are there still plans to merge this branch?

**Pull request closed without merging**
