### PR TITLE
Upgrade delve (fixes #2500, #2487, #2360, #2218)

### LINKED ISSUE #2500: Debug only works in the first try
- Plugin version (or commit hash): 0.11.1343
- IDE name and version: IntelliJ IDEA 2016.1 CE #IC-145.970
- Java version: JRE 1.8.74 amd64

- OS name and version: 
Windodws 8.1 x64
- What are you trying to do?
Debug a Go program
- What would you expect to happen?
Debug working on all reloads
- What happens?
Debug only works the firs time it's called

On cold boot and first debug, all works fine, here's the log:
[Cold Boot first Debug log.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/244840/Cold.Boot.first.Debug.log.txt)

On reloading the debug, it doesn't work, here's the log;
[Reload Debug.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/244844/Reload.Debug.txt)

Total log is here:
[Total log.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/244848/Total.log.txt)

The Go code:
[main.go.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/244853/main.go.txt)

Thank you

### PR DESCRIPTION
**Pull request by dlsniper**
If I've got the build id correctly from BinTray this should be it.

### CODE REVIEW

**Comment by kolkov** [comment]
And what about this? https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2347

**Comment by dlsniper** [comment]
Does delve support it now?

**Comment by kolkov** [comment]
I don't know ( but issues closed already
https://github.com/derekparker/delve/issues/426 
https://github.com/derekparker/delve/issues/455

**Comment by dlsniper** [comment]
From #2347 it seems that the issue is in delve and from derekparker/delve#426  it looks like there's no way to do it in delve either since it's related to how Go works. Thus the issue is with retrieving the value from Go which is not possible right now, so no, the issue you mentioned is not fixed (as it can't be fixed).

The other issue is still opened in delve so it's not going to be fixed by this PR / delve update.

Please help Derek and Alessandro and the other contributors of delve if you'd like to see more thins working as the plugin cannot support functionality which Delve doesn't have present.
Sorry I can't give you better news.

**Comment by kolkov** [comment]
Why the debugger still not working in the last version 0.12.1625?
IntelliJ IDEA 2016.2
Build #IU-162.1121.10, built on July 5, 2016
Licensed to Andrey Kolkov
You have perpetual fallback license for this version
Subscription is active until November 12, 2017
JRE: 1.8.0_25-b18 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Comment by dlsniper** [comment]
Because that branch hasn't been updated with the latest changes in master.
Please use IDEA 2016.1 or wait until 2016.2 catches up with the master branch.

**Comment by kolkov** [comment]
Ok! Thanks.)

**Comment by silasdavis** [comment]
This is still broken for me, using the go plugin version: 0.11.1636

and:

IntelliJ IDEA 2016.1.3
Build #IC-145.1617, built on June 3, 2016
JRE: 1.8.0_76-release-b198 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

I get:
```
could not launch process: Unreadable version number: could not read string len input/output error
```

**Comment by dlsniper** [comment]
@silasdavis please open a separate issue. Thank you

**Comment by kolkov** [comment]
@dlsniper Hi! When the changes are available in 2016.2?

**Comment by zolotov** [comment]
@kolkov in couple days

**Comment by ignatov** [comment]
Obsolete.

**Comment by gnufied** [comment]
Is this really fixed. I am still seeing this problem on Linux too:

```
/root/.IdeaIC2016.3/config/plugins/Go/lib/dlv/linux/dlv --listen=localhost:33577 --headless=true exec /tmp/kubeletgo -- -v 2 --api_servers=http://xaos.lan:8080 --address=0.0.0.0 --hostname_override=xaos.lan
GOROOT=/data/go
GOPATH=/home/shared/go_projects
/data/go/bin/go build -o /tmp/kubeletgo -gcflags "-N -l" /home/shared/go_projects/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go
could not launch process: Unreadable version number: could not read string len input/output error
```

**Comment by ignatov** [comment]
Hi @gnufied! Please try to use [Gogland](jetbrains.com/go); I suppose it's already fixed.

**Comment by gnufied** [comment]
Nope just tried with latest release and it still looks to be a problem:

```
GOROOT=/data/go
GOPATH=/home/shared/go_projects
/data/go/bin/go build -o /tmp/kubeletgo -gcflags "-N -l" /home/shared/go_projects/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go
/content/apps/Gogland-163.10615.22/bin/dlv --listen=localhost:45937 --headless=true --api-version=2 exec /tmp/kubeletgo -- -v 2 --api_servers=http://xaos.lan:8080 --address=0.0.0.0 --hostname_override=xaos.lan
could not launch process: Unreadable version number: could not read string len input/output error
```

I am starting Intellij as root user though because I need to start `kubelet` which requires sudo permission for properly starting up. I don't know if this problem is because of that but just for some background.

**Comment by dlsniper** [comment]
@gnufied what version of Go are you using to compile kubelet?

**Comment by gnufied** [comment]
Go version 1.7.1

btw I have tried nuking `.idea` directory inside project directory and even rebooted the system and problem still remains.

**Comment by dlsniper** [comment]
Please try Go 1.7.4 or 1.8 RC2, I'll try and replicate this as well. Thank you.

**Comment by gnufied** [comment]
Okay, I upgraded to Go 1.7.4, changed GOROOT and GOPATH and nuked existing `~/.Gog*` and `~/.IdeaIC*` and still exactly same error:

```
GOROOT=/home/root/goroot
GOPATH=/home/root/goprojects
/home/root/goroot/bin/go build -o /tmp/Kubeletgo -gcflags "-N -l" /home/root/goprojects/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go
/content/apps/Gogland-163.10615.22/bin/dlv --listen=localhost:41207 --headless=true --api-version=2 exec /tmp/Kubeletgo -- -v 2 --api_servers=http://xaos.lan:8080 --address=0.0.0.0 --hostname_override=xaos.lan
could not launch process: Unreadable version number: could not read string len input/output error
Process finished with exit code 1
```

The steps to reproduce:

1. Login as root 
2. Configure GOROOT and GOPATH as usual.
3. Clone `kubernetes` from github into a valid $GOPATH. such as `src/k8s.io/kubernetes`
4. Open kubernetes in Gogland
5. Edit configuration and create a configuration to launch `kubelet` executable. The corresponding Go file is present in `cmd/kubelet` directory of Kubernetes checkout.
6. At very minimum kubelet requires a valid `api-server`. You can specify any bogus server as well for sake of testing, I used above option.
7. Before starting kubelet make sure to have some breakpoints in codepath which is going to be executed by `kubelet`. For example - `pkg/util/mount/mount.go` 
8. Start Kubelet from Intellj and it fails to start with above error.

**Pull request merged**
