### PR TITLE
Add debugging to tests and single file configuration

### LINKED ISSUE #1855: Support debugging for tests
I have just tried using the new delve debugger integration, which appears to be a great start.  I am using IntelliJ 141.1532, and version 0.9.491 of the plugin (which claims to be an alpha version for 1.0.0).  I am using Go 1.4.2 sdk.

Anyway, it is possible to debug files and packages that have a 'main' method.  But there does not appear to be a way yet to debug tests, via the test integration within IntelliJ.

Is this something that could be added easily enough (or are there technical reasons preventing it?)

### PR DESCRIPTION
**Pull request by dlsniper**
Fixes #1855

### CODE REVIEW

**Comment by zolotov** [comment]
In the PR you rely on delve for building sources. That's why derekparker/delve#423 is blocker for you. Instead of that it's better to separate building and running/debugging binary file logic. In this case delve will have nothing to do with building and we will be able change building-logic in any way we want.

**Comment by dlsniper** [comment]
You are right. I'll update this accordingly.

**Comment by dlsniper** [comment]
Note for self: test flags for running a binary are sent with their prefix (`-test.run` instead of simply `-run`) but this could be unified regardless of debug mode or not to simplify the process so that regardless of `go test` or `dlv exec <binary> --` we send the same parameters.

**Comment by zolotov** [comment]
@dlsniper yep, this is exactly how I see it. The only hard issue here is preprocessing arguments. Note that all following arguments are needed to be processed (not only run): https://github.com/golang/go/blob/master/src/cmd/go/test.go#L126

**Comment by dlsniper** [comment]
Hi, I'm close to finishing this but I need some help.
Debugging a single file run works, so does the application (as it used to). However the issue is when running the tests under debugging.

The logs:
```
2016-03-24 23:08:54,248 [ 336834]   INFO -           #com.goide.dlv.DlvVm - OUT: {"method":"RPCServer.CreateBreakpoint","params":[{"file":"/home/florin/golang/src/github.com/dlsniper/u/tmp/mypack/dem_test.go","line":8}],"id":1} 
2016-03-24 23:08:54,248 [ 336834]   INFO -           #com.goide.dlv.DlvVm - OUT: {"method":"RPCServer.Command","params":[{"Name":"continue"}],"id":2} 
2016-03-24 23:08:54,249 [ 336835]   INFO -           #com.goide.dlv.DlvVm - IN: {"id":1,"result":{"id":1,"name":"","addr":4709431,"file":"/home/florin/golang/src/github.com/dlsniper/u/tmp/mypack/dem_test.go","line":8,"functionName":"github.com/dlsniper/u/tmp/mypack_test.TestDemo","Cond":"","continue":false,"stacktrace":0,"goroutine":false,"hitCount":{},"totalHitCount":0},"error":null} 
2016-03-24 23:08:54,253 [ 336839]   INFO -           #com.goide.dlv.DlvVm - IN: {"id":2,"result":{"Threads":null,"exited":true,"exitStatus":0},"error":null} 
2016-03-24 23:08:54,255 [ 336841]   INFO -           #com.goide.dlv.DlvVm - OUT: {"method":"RPCServer.Detach","params":[true],"id":3} 
2016-03-24 23:08:54,267 [ 336853]   INFO -           #com.goide.dlv.DlvVm - IN: {"id":3,"result":0,"error":null} 
2016-03-24 23:08:54,323 [ 336909]   INFO - #com.goide.dlv.DlvDebugProcess - Connection closed 
org.jetbrains.concurrency.Promise$MessageError: Connection closed
```

and the output:
```
/usr/local/go1.6/bin/go test -o "/tmp/TestDemo in dem_test.go1go" -c -gcflags "-N -l" github.com/dlsniper/u/tmp/mypack
/home/florin/IdeaProjects/google-go-lang-idea-plugin/build/idea-sandbox/plugins/Go/lib/dlv/linux/dlv --listen=localhost:41587 --headless=true exec "/tmp/TestDemo in dem_test.go1go" -- -test.v -test.run='^TestDemo$'
Testing started at 23:08 ...
PASS
```

which is flagged as: ` Test framework quit unexpectedly `.

When running the the following commands:

```
/usr/local/go1.6/bin/go test -o "/tmp/TestDemo in dem_test.gogo" -c -gcflags "-N -l" github.com/dlsniper/u/tmp/mypack
/home/florin/IdeaProjects/google-go-lang-idea-plugin/build/idea-sandbox/plugins/Go/lib/dlv/linux/dlv exec "/tmp/TestDemo in dem_test.gogo" -- -test.v -test.run='^TestDemo$'
```

with the output:
```
=== RUN   TestDemo
--- PASS: TestDemo (0.00s)
PASS
Process 16919 has exited with status 0
```

and setting the breakpoint on the line correctly that works as expected and the debugger stops. So does running the tests without the debugger:

```
/usr/local/go1.6/bin/go test -o "/tmp/TestDemo in dem_test.gogo" -c -gcflags "-N -l" github.com/dlsniper/u/tmp/mypack
"/tmp/TestDemo in dem_test.gogo" -test.v -test.run='^TestDemo$'
```

Which has the output:
```
=== RUN   TestDemo
--- PASS: TestDemo (0.00s)
PASS
```

Can you please have a look on this? Thank you!

**Comment by zolotov** [comment]
Please do not try to implement everything in a single PR, it would take forever until it would be fully reviewed/reworked until merge. 
First of all make test run configurations work via building runner with proper separation tool/test parameters. Enabling debugging for tests and reimplementing `run file configuration` extract into separate PRs. Thanks.

**Comment by dlsniper** [comment]
Understood. One question. Since I'm reworking this whole run configuration part, would it be also ok if at the end of the process we remove the the separate Go Single File configuration and merge the functionality into the Go Application configuration? I'll submit the first PR to run tests via GoBuildingRunner soon. Thank you.

**Comment by zolotov** [comment]
>  Since I'm reworking this whole run configuration part, would it be also ok if at the end of the process we remove the the separate Go Single File configuration and merge the functionality into the Go Application configuration? 

Sure, I think it's logical continuation of this issue, as well as adding multi-file run configuration

**Pull request closed without merging**
