### PR TITLE
Initial support for IDEA 16

### LINKED ISSUE #2123: IDEA 16 EAP is not supported yet
this plugin does not support IDEA EAP 16

### LINKED ISSUE #2210: Plugin is not compatible with IDEA EAP 16
Is there a way I can help on this topic ?

### PR DESCRIPTION
**Pull request by dlsniper**
Fixes #2123, fixes #2210

### CODE REVIEW

**Comment by dlsniper** [comment]
For some reason the debugger doesn't appear to stop right now... Further investigation is needed.

**Comment by dlsniper** [comment]
@ignatov this PR solves partially the issue with IDEA 16. Delve works correctly and all looks good for the end-user. However the performance tests fail, see: https://teamcity.jetbrains.com/viewLog.html?buildId=664355&tab=buildResultsDiv&buildTypeId=IntellijIdeaPlugins_Go_PerformanceTests

I can fix one of them, the `testUnusedFunction` as I can have a look into what's happening there.
However, I don't really know yet how to fix the `testCompletionPerformance` one (maybe @zolotov could help me out a bit there?)

Finally, on my laptop I have the following test failing consistently as well:

```
[ 145292]   WARN - j.testFramework.TeamCityLogger - Another epic fail (remaining attempts: 3): parserAndStubs: 986% longer. Expected: 2211ms (2.2s). Actual: 24020ms (24.0s). Timings: CPU=67 (33% of the etalon), I/O=11 (11% of the etalon), total=78 (17% of the etalon) 8 cores. 
Another epic fail (remaining attempts: 3): parserAndStubs: 986% longer. Expected: 2211ms (2.2s). Actual: 24020ms (24.0s). Timings: CPU=67 (33% of the etalon), I/O=11 (11% of the etalon), total=78 (17% of the etalon) 8 cores.
[ 163148]   WARN - j.testFramework.TeamCityLogger - Another epic fail (remaining attempts: 2): parserAndStubs: 693% longer. Expected: 2211ms (2.2s). Actual: 17546ms (17.5s). Timings: CPU=67 (33% of the etalon), I/O=11 (11% of the etalon), total=78 (17% of the etalon) 8 cores. 
Another epic fail (remaining attempts: 2): parserAndStubs: 693% longer. Expected: 2211ms (2.2s). Actual: 17546ms (17.5s). Timings: CPU=67 (33% of the etalon), I/O=11 (11% of the etalon), total=78 (17% of the etalon) 8 cores.
[ 182818]   WARN - j.testFramework.TeamCityLogger - Another epic fail (remaining attempts: 1): parserAndStubs: 775% longer. Expected: 2211ms (2.2s). Actual: 19353ms (19.4s). Timings: CPU=67 (33% of the etalon), I/O=11 (11% of the etalon), total=78 (17% of the etalon) 8 cores. 
Another epic fail (remaining attempts: 1): parserAndStubs: 775% longer. Expected: 2211ms (2.2s). Actual: 19353ms (19.4s). Timings: CPU=67 (33% of the etalon), I/O=11 (11% of the etalon), total=78 (17% of the etalon) 8 cores.

parserAndStubs: 826% longer. Expected: 2211ms (2.2s). Actual: 20490ms (20.5s). Timings: CPU=67 (33% of the etalon), I/O=11 (11% of the etalon), total=78 (17% of the etalon) 8 cores.
junit.framework.AssertionFailedError: parserAndStubs: 826% longer. Expected: 2211ms (2.2s). Actual: 20490ms (20.5s). Timings: CPU=67 (33% of the etalon), I/O=11 (11% of the etalon), total=78 (17% of the etalon) 8 cores.
	at com.intellij.testFramework.PlatformTestUtil$TestInfo.assertTiming(PlatformTestUtil.java:581)
	at com.goide.GoPerformanceTest.testParserAndStubs(GoPerformanceTest.java:216)
```

Please let me know if I can help out investigating any of those. Thank you.

**Comment by dlsniper** [comment]
Please disregard the part about the `testUnusedFunction` I've forgot to update my branch, sorry. The other two issues are still present.

**Comment by dlsniper** [comment]
I've tested out and the only breaking change in the code is this: `protected final JsonWriter writer = getWriter();` otherwise this PR would work against IDEA 15.0.3 EAP.

The problem is that this in: `org.jetbrains.jsonProtocol.OutMessage` where the field:
```kotlin
@JvmField
val writer = JsonWriter(ByteBufUtf8Writer(buffer))
```
has been changed to
```kotlin
val writer = JsonWriter(ByteBufUtf8Writer(buffer))
```

Hope it helps.

**Comment by zolotov** [comment]
Thanks! Your changes were merged manually into `master` (partially) and `144` branch.

**Comment by dlsniper** [comment]
@zolotov is there any way I could in the issue described here about the performance tests: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/2211#issuecomment-168715191 ? I've seen this doesn't happen on YouTrack

**Comment by zolotov** [comment]
@dlsniper it will be fixed after

**Pull request closed without merging**
